version: "3.8"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.49.0-rc.1
    ports:
      - "9090:9090"
    volumes:
      - "./configs/prometheus.yml:/etc/prometheus/prometheus.yml"
      - type: volume
        source: prometheus-data
        target: /prometheus


  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.15-ubuntu
    ports:
      - "3004:3000"
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:

