version: "3.8"
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7.44-oracle
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql-data:
