version: "3.8"


services:
  redis-node-1:
    container_name: redis-node-1
    image: 'bitnami/redis:6.2.14-debian-11-r1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-node-1-data
        target: /bitnami/redis/data


  redis-node-2:
    container_name: redis-node-2
    image: 'bitnami/redis:6.2.14-debian-11-r1'
    ports:
      - "6378:6378"
    depends_on:
      - redis-node-1
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-node-1
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - type: volume
        source: redis-node-2-data
        target: /bitnami/redis/data

volumes:
  redis-node-1-data:
  redis-node-2-data:

